
@host = http://localhost:5064

POST {{host}}/auth/register
Content-Type: application/json

{
    "FirstName": "",
    "LastName": "",
    "Email": "wilson.njoroge@gmail.com",
    "Password": "Wilson.123"
}

