
@host = http://localhost:5064
@hostId = 1234567890
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZjg0ZGJmOS1mYzFhLTRhZmEtOWIwMi0zNmEwZmQ3N2U3NWEiLCJnaXZlbl9uYW1lIjoiV2lsc29uIiwiZmFtaWx5X25hbWUiOiJOam9yb2dlIiwianRpIjoiMDU3ODY2YjAtMTg5My00ZjhjLTgxZWQtNWYzZGYwYTI4ZjNkIiwiZXhwIjoxNzE3ODM2NzAxLCJpc3MiOiJCdXJiZXJEaW5uZXIiLCJhdWQiOiJCdXJiZXJEaW5uZXIifQ.rqbxMpcyyKKrvXugKBvbPXQ4fpP1MXBbt_K9wRr4Dw0

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "hostId": "" ,
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}
