

@host = http://localhost:5064
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMDU0ZGEzNC02ZjU0LTQxZjAtODljNy1mOWIyYjBiYzViYjYiLCJnaXZlbl9uYW1lIjoiV2lsc29uIiwiZmFtaWx5X25hbWUiOiJOam9yb2dlIiwianRpIjoiOGJjODI4ZjQtMDc5ZC00YmZmLWE4OGEtYWM5NmZkZTA5N2VlIiwiZXhwIjoxNzE3ODM3Mjk1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwNjQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwNjQifQ.OYQLb7Ojcer-hA1wMYLeAdQsF1rQUclKBAp9_YbNWWw

GET {{host}}/dinners

Authorization: Bearer {{token}}
