

@host = http://localhost:5064

GET {{host}}/dinners

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZGQxMDRlMi1jYjU4LTRlNzktYWU0My0wMjQ5NDJhYjQ4MDciLCJnaXZlbl9uYW1lIjoiV2lsc29uIiwiZmFtaWx5X25hbWUiOiJOam9yb2dlIiwianRpIjoiMGRmZmE0MzYtODcyYi00Y2U0LWJhMGUtMTI3MzU0ZmZiYzczIiwiZXhwIjoxNzE3NTI4OTg4LCJpc3MiOiJCdXJiZXJEaW5uZXIiLCJhdWQiOiJCdXJiZXJEaW5uZXIifQ.7VmxQULck1OBgzI8lxn8eoMLbgWdAO3C3nZzi-9jZa4
